### ISSUE TITLE
Improve launching robots: decide on which to focus.

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/robotDevastation-robots#26]
E.g.
- Remote robots such as RD1, RD2, and potentially RD "Ambassator" (see #21) still suffer from #16.
- LaserTowerOfDeath mainly lacks documentation, see #25.

**Comment by David-Estevez** [comment]
The original roadmap proposed working with "wired" robots (i.e. turrets) because they are (in principle) easier to setup and easier to work with when developing the game.

So I vote for working on turret-like robots first, and them move on remote robots. 

It is outside the scope of this repo, but we also have to have in mind [milestone 5](https://github.com/asrob-uc3m/robotDevastation/milestone/5) from RobotDevastation main repo.

**Comment by jgvictores** [comment]
Software-wise:
- Locally connected turrets are supported, see [Launch Robot Devastation - With Fake Motors And With PC Webcam](https://github.com/asrob-uc3m/robotDevastation-user-manual/blob/a91657b481702fd1a795322e68d017efca3b3665/en/launch-robot-devastation---LaserTowerOfDeath-with-webcam.md). ToDo:
  - [x] https://github.com/asrob-uc3m/robotDevastation/issues/91
- Remotely connected turrets have multiple issues. To name some:
  - [x] #29 
  - [ ] #9

**Comment by jgvictores** [comment]
More related: #21 #34

**Comment by jgvictores** [comment]
Will focus on simulated robots for now, see #36
